openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: local dev server 
  - url: https://task-api-backend-jmi2.onrender.com
    description: Prod server
tags:
  - name: Tasks
    description: Tasks - Related Endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
